name: flutter_application_3
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  
  assets:
    - images/
    - images/pic1.jpg
    

 
  fonts:
    - family: Monoton
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        
    - family: Playball
      fonts:
        - asset: fonts/Playball-Regular.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
